version: '3.7'
services:
  mysql:
    image: postgres:12.0-alphine
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=1
      - POSTGRES_USER=ddn
      - PGDATA=var/lib/postgresql/data
      - POSTGRES_DB=db
